export const PRODUCTS = [
    {category: 'Électronique', price: '999€', stocked: true, name: 'DJI Mavic Air 2'},
    {category: 'Électronique', price: '399€', stocked: true, name: 'DJI Osmo Mobile 3'},
    {category: 'Électronique', price: '749€', stocked: false, name: 'DJI Mavic Mini'},
    {category: 'Électronique', price: '1899€', stocked: true, name: 'DJI Phantom 4 Pro'},
    {category: 'Électronique', price: '299€', stocked: true, name: 'DJI Ronin-SC'},
    {category: 'Électronique', price: '419€', stocked: false, name: 'DJI FPV Goggles'},
    {category: 'Électronique', price: '539€', stocked: true, name: 'DJI Osmo Action'},
    {category: 'Électronique', price: '999€', stocked: true, name: 'DJI Mavic 2 Pro'},
    {category: 'Électronique', price: '729€', stocked: false, name: 'DJI Mavic Air'},
    {category: 'Électronique', price: '1199€', stocked: true, name: 'DJI Inspire 2'},

    {category: 'Vêtements', price: '60€', stocked: true, name: 'Superdry Hoodie'},
    {category: 'Vêtements', price: '45€', stocked: false, name: 'Celio Jeans'},
    {category: 'Vêtements', price: '30€', stocked: true, name: 'Superdry T-Shirt'},
    {category: 'Vêtements', price: '100€', stocked: true, name: 'Superdry Windcheater'},
    {category: 'Vêtements', price: '85€', stocked: false, name: 'Celio Leather Jacket'},
    {category: 'Vêtements', price: '25€', stocked: true, name: 'Celio Polo'},
    {category: 'Vêtements', price: '50€', stocked: true, name: 'Superdry Shorts'},
    {category: 'Vêtements', price: '35€', stocked: false, name: 'Superdry Socks Pack'},
    {category: 'Vêtements', price: '20€', stocked: true, name: 'Celio Cap'},
    {category: 'Vêtements', price: '120€', stocked: true, name: 'Superdry Parka'},

    {category: 'Accessoires Informatiques', price: '25€', stocked: true, name: 'Clavier Mécanique'},
    {category: 'Accessoires Informatiques', price: '35€', stocked: false, name: 'Souris Gaming RGB'},
    {category: 'Accessoires Informatiques', price: '299€', stocked: true, name: 'Écran 4K 27"'},
    {category: 'Accessoires Informatiques', price: '19€', stocked: true, name: 'Tapis de Souris XXL'},
    {category: 'Accessoires Informatiques', price: '150€', stocked: false, name: 'Disque Dur Externe 1To SSD'},
    {category: 'Accessoires Informatiques', price: '90€', stocked: true, name: 'Webcam HD'},
    {category: 'Accessoires Informatiques', price: '50€', stocked: true, name: 'Microphone USB'},
    {category: 'Accessoires Informatiques', price: '110€', stocked: false, name: 'Casque Audio Bluetooth'},
    {category: 'Accessoires Informatiques', price: '230€', stocked: true, name: 'Imprimante Laser Couleur'},
    {category: 'Accessoires Informatiques', price: '80€', stocked: true, name: 'Routeur WiFi 6'}
];